# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-slim

# Install Python3 and build dependencies
RUN apt-get update && apt-get install -y \
    python3 python3-venv python3-pip build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy Python requirements and install into venv
COPY requirements.txt ./
RUN python3 -m venv .venv \
    && . .venv/bin/activate \
    && pip install --no-cache-dir -r requirements.txt

# Copy Node.js files and install dependencies
COPY package.json package-lock.json index.js baas_sms_mcp ./
RUN npm install --production

# Copy rest of code
COPY . .

# Ensure venv is used by default
ENV PATH="/app/.venv/bin:$PATH"

# Entrypoint
ENTRYPOINT ["node", "index.js"]
