# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install Node.js and npm
RUN apt-get update && \
    apt-get install -y --no-install-recommends nodejs npm && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY package.json package-lock.json requirements.txt index.js llms.txt ./
COPY baas_sms_mcp ./baas_sms_mcp

# Install Python dependencies
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# Install Node dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Default command
CMD ["node", "index.js"]
